// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"webreader/ent/category"
	"webreader/ent/predicate"
	"webreader/ent/ranobe"
	"webreader/ent/schema/ulid"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RanobeQuery is the builder for querying Ranobe entities.
type RanobeQuery struct {
	config
	limit               *int
	offset              *int
	unique              *bool
	order               []OrderFunc
	fields              []string
	predicates          []predicate.Ranobe
	withCategories      *CategoryQuery
	modifiers           []func(*sql.Selector)
	loadTotal           []func(context.Context, []*Ranobe) error
	withNamedCategories map[string]*CategoryQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RanobeQuery builder.
func (rq *RanobeQuery) Where(ps ...predicate.Ranobe) *RanobeQuery {
	rq.predicates = append(rq.predicates, ps...)
	return rq
}

// Limit adds a limit step to the query.
func (rq *RanobeQuery) Limit(limit int) *RanobeQuery {
	rq.limit = &limit
	return rq
}

// Offset adds an offset step to the query.
func (rq *RanobeQuery) Offset(offset int) *RanobeQuery {
	rq.offset = &offset
	return rq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rq *RanobeQuery) Unique(unique bool) *RanobeQuery {
	rq.unique = &unique
	return rq
}

// Order adds an order step to the query.
func (rq *RanobeQuery) Order(o ...OrderFunc) *RanobeQuery {
	rq.order = append(rq.order, o...)
	return rq
}

// QueryCategories chains the current query on the "categories" edge.
func (rq *RanobeQuery) QueryCategories() *CategoryQuery {
	query := &CategoryQuery{config: rq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(ranobe.Table, ranobe.FieldID, selector),
			sqlgraph.To(category.Table, category.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, ranobe.CategoriesTable, ranobe.CategoriesPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Ranobe entity from the query.
// Returns a *NotFoundError when no Ranobe was found.
func (rq *RanobeQuery) First(ctx context.Context) (*Ranobe, error) {
	nodes, err := rq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{ranobe.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rq *RanobeQuery) FirstX(ctx context.Context) *Ranobe {
	node, err := rq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Ranobe ID from the query.
// Returns a *NotFoundError when no Ranobe ID was found.
func (rq *RanobeQuery) FirstID(ctx context.Context) (id ulid.ID, err error) {
	var ids []ulid.ID
	if ids, err = rq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{ranobe.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rq *RanobeQuery) FirstIDX(ctx context.Context) ulid.ID {
	id, err := rq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Ranobe entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Ranobe entity is found.
// Returns a *NotFoundError when no Ranobe entities are found.
func (rq *RanobeQuery) Only(ctx context.Context) (*Ranobe, error) {
	nodes, err := rq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{ranobe.Label}
	default:
		return nil, &NotSingularError{ranobe.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rq *RanobeQuery) OnlyX(ctx context.Context) *Ranobe {
	node, err := rq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Ranobe ID in the query.
// Returns a *NotSingularError when more than one Ranobe ID is found.
// Returns a *NotFoundError when no entities are found.
func (rq *RanobeQuery) OnlyID(ctx context.Context) (id ulid.ID, err error) {
	var ids []ulid.ID
	if ids, err = rq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{ranobe.Label}
	default:
		err = &NotSingularError{ranobe.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rq *RanobeQuery) OnlyIDX(ctx context.Context) ulid.ID {
	id, err := rq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Ranobes.
func (rq *RanobeQuery) All(ctx context.Context) ([]*Ranobe, error) {
	if err := rq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return rq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (rq *RanobeQuery) AllX(ctx context.Context) []*Ranobe {
	nodes, err := rq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Ranobe IDs.
func (rq *RanobeQuery) IDs(ctx context.Context) ([]ulid.ID, error) {
	var ids []ulid.ID
	if err := rq.Select(ranobe.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rq *RanobeQuery) IDsX(ctx context.Context) []ulid.ID {
	ids, err := rq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rq *RanobeQuery) Count(ctx context.Context) (int, error) {
	if err := rq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return rq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (rq *RanobeQuery) CountX(ctx context.Context) int {
	count, err := rq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rq *RanobeQuery) Exist(ctx context.Context) (bool, error) {
	if err := rq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return rq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (rq *RanobeQuery) ExistX(ctx context.Context) bool {
	exist, err := rq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RanobeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rq *RanobeQuery) Clone() *RanobeQuery {
	if rq == nil {
		return nil
	}
	return &RanobeQuery{
		config:         rq.config,
		limit:          rq.limit,
		offset:         rq.offset,
		order:          append([]OrderFunc{}, rq.order...),
		predicates:     append([]predicate.Ranobe{}, rq.predicates...),
		withCategories: rq.withCategories.Clone(),
		// clone intermediate query.
		sql:    rq.sql.Clone(),
		path:   rq.path,
		unique: rq.unique,
	}
}

// WithCategories tells the query-builder to eager-load the nodes that are connected to
// the "categories" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *RanobeQuery) WithCategories(opts ...func(*CategoryQuery)) *RanobeQuery {
	query := &CategoryQuery{config: rq.config}
	for _, opt := range opts {
		opt(query)
	}
	rq.withCategories = query
	return rq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Ranobe.Query().
//		GroupBy(ranobe.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rq *RanobeQuery) GroupBy(field string, fields ...string) *RanobeGroupBy {
	grbuild := &RanobeGroupBy{config: rq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return rq.sqlQuery(ctx), nil
	}
	grbuild.label = ranobe.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Ranobe.Query().
//		Select(ranobe.FieldCreatedAt).
//		Scan(ctx, &v)
func (rq *RanobeQuery) Select(fields ...string) *RanobeSelect {
	rq.fields = append(rq.fields, fields...)
	selbuild := &RanobeSelect{RanobeQuery: rq}
	selbuild.label = ranobe.Label
	selbuild.flds, selbuild.scan = &rq.fields, selbuild.Scan
	return selbuild
}

func (rq *RanobeQuery) prepareQuery(ctx context.Context) error {
	for _, f := range rq.fields {
		if !ranobe.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rq.path != nil {
		prev, err := rq.path(ctx)
		if err != nil {
			return err
		}
		rq.sql = prev
	}
	return nil
}

func (rq *RanobeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Ranobe, error) {
	var (
		nodes       = []*Ranobe{}
		_spec       = rq.querySpec()
		loadedTypes = [1]bool{
			rq.withCategories != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Ranobe).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Ranobe{config: rq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(rq.modifiers) > 0 {
		_spec.Modifiers = rq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rq.withCategories; query != nil {
		if err := rq.loadCategories(ctx, query, nodes,
			func(n *Ranobe) { n.Edges.Categories = []*Category{} },
			func(n *Ranobe, e *Category) { n.Edges.Categories = append(n.Edges.Categories, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range rq.withNamedCategories {
		if err := rq.loadCategories(ctx, query, nodes,
			func(n *Ranobe) { n.appendNamedCategories(name) },
			func(n *Ranobe, e *Category) { n.appendNamedCategories(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range rq.loadTotal {
		if err := rq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rq *RanobeQuery) loadCategories(ctx context.Context, query *CategoryQuery, nodes []*Ranobe, init func(*Ranobe), assign func(*Ranobe, *Category)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[ulid.ID]*Ranobe)
	nids := make(map[ulid.ID]map[*Ranobe]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(ranobe.CategoriesTable)
		s.Join(joinT).On(s.C(category.FieldID), joinT.C(ranobe.CategoriesPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(ranobe.CategoriesPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(ranobe.CategoriesPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	neighbors, err := query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
		assign := spec.Assign
		values := spec.ScanValues
		spec.ScanValues = func(columns []string) ([]any, error) {
			values, err := values(columns[1:])
			if err != nil {
				return nil, err
			}
			return append([]any{new(ulid.ID)}, values...), nil
		}
		spec.Assign = func(columns []string, values []any) error {
			outValue := *values[0].(*ulid.ID)
			inValue := *values[1].(*ulid.ID)
			if nids[inValue] == nil {
				nids[inValue] = map[*Ranobe]struct{}{byID[outValue]: struct{}{}}
				return assign(columns[1:], values[1:])
			}
			nids[inValue][byID[outValue]] = struct{}{}
			return nil
		}
	})
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "categories" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (rq *RanobeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rq.querySpec()
	if len(rq.modifiers) > 0 {
		_spec.Modifiers = rq.modifiers
	}
	_spec.Node.Columns = rq.fields
	if len(rq.fields) > 0 {
		_spec.Unique = rq.unique != nil && *rq.unique
	}
	return sqlgraph.CountNodes(ctx, rq.driver, _spec)
}

func (rq *RanobeQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := rq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (rq *RanobeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   ranobe.Table,
			Columns: ranobe.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: ranobe.FieldID,
			},
		},
		From:   rq.sql,
		Unique: true,
	}
	if unique := rq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := rq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ranobe.FieldID)
		for i := range fields {
			if fields[i] != ranobe.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rq *RanobeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rq.driver.Dialect())
	t1 := builder.Table(ranobe.Table)
	columns := rq.fields
	if len(columns) == 0 {
		columns = ranobe.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rq.sql != nil {
		selector = rq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rq.unique != nil && *rq.unique {
		selector.Distinct()
	}
	for _, p := range rq.predicates {
		p(selector)
	}
	for _, p := range rq.order {
		p(selector)
	}
	if offset := rq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedCategories tells the query-builder to eager-load the nodes that are connected to the "categories"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (rq *RanobeQuery) WithNamedCategories(name string, opts ...func(*CategoryQuery)) *RanobeQuery {
	query := &CategoryQuery{config: rq.config}
	for _, opt := range opts {
		opt(query)
	}
	if rq.withNamedCategories == nil {
		rq.withNamedCategories = make(map[string]*CategoryQuery)
	}
	rq.withNamedCategories[name] = query
	return rq
}

// RanobeGroupBy is the group-by builder for Ranobe entities.
type RanobeGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rgb *RanobeGroupBy) Aggregate(fns ...AggregateFunc) *RanobeGroupBy {
	rgb.fns = append(rgb.fns, fns...)
	return rgb
}

// Scan applies the group-by query and scans the result into the given value.
func (rgb *RanobeGroupBy) Scan(ctx context.Context, v any) error {
	query, err := rgb.path(ctx)
	if err != nil {
		return err
	}
	rgb.sql = query
	return rgb.sqlScan(ctx, v)
}

func (rgb *RanobeGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range rgb.fields {
		if !ranobe.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := rgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (rgb *RanobeGroupBy) sqlQuery() *sql.Selector {
	selector := rgb.sql.Select()
	aggregation := make([]string, 0, len(rgb.fns))
	for _, fn := range rgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(rgb.fields)+len(rgb.fns))
		for _, f := range rgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(rgb.fields...)...)
}

// RanobeSelect is the builder for selecting fields of Ranobe entities.
type RanobeSelect struct {
	*RanobeQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (rs *RanobeSelect) Scan(ctx context.Context, v any) error {
	if err := rs.prepareQuery(ctx); err != nil {
		return err
	}
	rs.sql = rs.RanobeQuery.sqlQuery(ctx)
	return rs.sqlScan(ctx, v)
}

func (rs *RanobeSelect) sqlScan(ctx context.Context, v any) error {
	rows := &sql.Rows{}
	query, args := rs.sql.Query()
	if err := rs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
