// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"webreader/ent/category"
	"webreader/ent/ranobe"
	"webreader/ent/schema/ulid"
	"webreader/ent/tag"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RanobeCreate is the builder for creating a Ranobe entity.
type RanobeCreate struct {
	config
	mutation *RanobeMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (rc *RanobeCreate) SetCreatedAt(t time.Time) *RanobeCreate {
	rc.mutation.SetCreatedAt(t)
	return rc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (rc *RanobeCreate) SetNillableCreatedAt(t *time.Time) *RanobeCreate {
	if t != nil {
		rc.SetCreatedAt(*t)
	}
	return rc
}

// SetUpdatedAt sets the "updated_at" field.
func (rc *RanobeCreate) SetUpdatedAt(t time.Time) *RanobeCreate {
	rc.mutation.SetUpdatedAt(t)
	return rc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (rc *RanobeCreate) SetNillableUpdatedAt(t *time.Time) *RanobeCreate {
	if t != nil {
		rc.SetUpdatedAt(*t)
	}
	return rc
}

// SetName sets the "name" field.
func (rc *RanobeCreate) SetName(s string) *RanobeCreate {
	rc.mutation.SetName(s)
	return rc
}

// SetEngName sets the "engName" field.
func (rc *RanobeCreate) SetEngName(s string) *RanobeCreate {
	rc.mutation.SetEngName(s)
	return rc
}

// SetRusName sets the "rusName" field.
func (rc *RanobeCreate) SetRusName(s string) *RanobeCreate {
	rc.mutation.SetRusName(s)
	return rc
}

// SetSummary sets the "summary" field.
func (rc *RanobeCreate) SetSummary(s string) *RanobeCreate {
	rc.mutation.SetSummary(s)
	return rc
}

// SetReleaseDate sets the "releaseDate" field.
func (rc *RanobeCreate) SetReleaseDate(i int) *RanobeCreate {
	rc.mutation.SetReleaseDate(i)
	return rc
}

// SetID sets the "id" field.
func (rc *RanobeCreate) SetID(u ulid.ID) *RanobeCreate {
	rc.mutation.SetID(u)
	return rc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (rc *RanobeCreate) SetNillableID(u *ulid.ID) *RanobeCreate {
	if u != nil {
		rc.SetID(*u)
	}
	return rc
}

// AddCategoryIDs adds the "categories" edge to the Category entity by IDs.
func (rc *RanobeCreate) AddCategoryIDs(ids ...ulid.ID) *RanobeCreate {
	rc.mutation.AddCategoryIDs(ids...)
	return rc
}

// AddCategories adds the "categories" edges to the Category entity.
func (rc *RanobeCreate) AddCategories(c ...*Category) *RanobeCreate {
	ids := make([]ulid.ID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return rc.AddCategoryIDs(ids...)
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (rc *RanobeCreate) AddTagIDs(ids ...ulid.ID) *RanobeCreate {
	rc.mutation.AddTagIDs(ids...)
	return rc
}

// AddTags adds the "tags" edges to the Tag entity.
func (rc *RanobeCreate) AddTags(t ...*Tag) *RanobeCreate {
	ids := make([]ulid.ID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return rc.AddTagIDs(ids...)
}

// Mutation returns the RanobeMutation object of the builder.
func (rc *RanobeCreate) Mutation() *RanobeMutation {
	return rc.mutation
}

// Save creates the Ranobe in the database.
func (rc *RanobeCreate) Save(ctx context.Context) (*Ranobe, error) {
	var (
		err  error
		node *Ranobe
	)
	rc.defaults()
	if len(rc.hooks) == 0 {
		if err = rc.check(); err != nil {
			return nil, err
		}
		node, err = rc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RanobeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = rc.check(); err != nil {
				return nil, err
			}
			rc.mutation = mutation
			if node, err = rc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(rc.hooks) - 1; i >= 0; i-- {
			if rc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = rc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, rc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Ranobe)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from RanobeMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (rc *RanobeCreate) SaveX(ctx context.Context) *Ranobe {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *RanobeCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *RanobeCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rc *RanobeCreate) defaults() {
	if _, ok := rc.mutation.CreatedAt(); !ok {
		v := ranobe.DefaultCreatedAt()
		rc.mutation.SetCreatedAt(v)
	}
	if _, ok := rc.mutation.UpdatedAt(); !ok {
		v := ranobe.DefaultUpdatedAt()
		rc.mutation.SetUpdatedAt(v)
	}
	if _, ok := rc.mutation.ID(); !ok {
		v := ranobe.DefaultID()
		rc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *RanobeCreate) check() error {
	if _, ok := rc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Ranobe.created_at"`)}
	}
	if _, ok := rc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Ranobe.updated_at"`)}
	}
	if _, ok := rc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Ranobe.name"`)}
	}
	if _, ok := rc.mutation.EngName(); !ok {
		return &ValidationError{Name: "engName", err: errors.New(`ent: missing required field "Ranobe.engName"`)}
	}
	if _, ok := rc.mutation.RusName(); !ok {
		return &ValidationError{Name: "rusName", err: errors.New(`ent: missing required field "Ranobe.rusName"`)}
	}
	if _, ok := rc.mutation.Summary(); !ok {
		return &ValidationError{Name: "summary", err: errors.New(`ent: missing required field "Ranobe.summary"`)}
	}
	if _, ok := rc.mutation.ReleaseDate(); !ok {
		return &ValidationError{Name: "releaseDate", err: errors.New(`ent: missing required field "Ranobe.releaseDate"`)}
	}
	return nil
}

func (rc *RanobeCreate) sqlSave(ctx context.Context) (*Ranobe, error) {
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*ulid.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	return _node, nil
}

func (rc *RanobeCreate) createSpec() (*Ranobe, *sqlgraph.CreateSpec) {
	var (
		_node = &Ranobe{config: rc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: ranobe.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: ranobe.FieldID,
			},
		}
	)
	if id, ok := rc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := rc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: ranobe.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := rc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: ranobe.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := rc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: ranobe.FieldName,
		})
		_node.Name = value
	}
	if value, ok := rc.mutation.EngName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: ranobe.FieldEngName,
		})
		_node.EngName = value
	}
	if value, ok := rc.mutation.RusName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: ranobe.FieldRusName,
		})
		_node.RusName = value
	}
	if value, ok := rc.mutation.Summary(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: ranobe.FieldSummary,
		})
		_node.Summary = value
	}
	if value, ok := rc.mutation.ReleaseDate(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: ranobe.FieldReleaseDate,
		})
		_node.ReleaseDate = value
	}
	if nodes := rc.mutation.CategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   ranobe.CategoriesTable,
			Columns: ranobe.CategoriesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: category.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := rc.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   ranobe.TagsTable,
			Columns: ranobe.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: tag.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RanobeCreateBulk is the builder for creating many Ranobe entities in bulk.
type RanobeCreateBulk struct {
	config
	builders []*RanobeCreate
}

// Save creates the Ranobe entities in the database.
func (rcb *RanobeCreateBulk) Save(ctx context.Context) ([]*Ranobe, error) {
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Ranobe, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RanobeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *RanobeCreateBulk) SaveX(ctx context.Context) []*Ranobe {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *RanobeCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *RanobeCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}
