// Code generated by ent, DO NOT EDIT.

package category

import (
	"time"
	"webreader/ent/schema/ulid"
)

const (
	// Label holds the string label denoting the category type in the database.
	Label = "category"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// EdgeRanobes holds the string denoting the ranobes edge name in mutations.
	EdgeRanobes = "ranobes"
	// Table holds the table name of the category in the database.
	Table = "categories"
	// RanobesTable is the table that holds the ranobes relation/edge. The primary key declared below.
	RanobesTable = "ranobe_categories"
	// RanobesInverseTable is the table name for the Ranobe entity.
	// It exists in this package in order to avoid circular dependency with the "ranobe" package.
	RanobesInverseTable = "ranobes"
)

// Columns holds all SQL columns for category fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldDescription,
}

var (
	// RanobesPrimaryKey and RanobesColumn2 are the table columns denoting the
	// primary key for the ranobes relation (M2M).
	RanobesPrimaryKey = []string{"ranobe_id", "category_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() ulid.ID
)
