// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Ranobe is the predicate function for ranobe builders.
type Ranobe func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// Todo is the predicate function for todo builders.
type Todo func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
